List<String> places = [
  "Budanilkantha",
  "New Baneshwor",
  "Koteshwor",
  "3 Kune",
  "Tripureshwor",
  "Old Baneshwor",
  "Thamel",
  "Ratna Park",
  "Chabahil",
  "Shantinagar",
  "Thapathali",
  "Maitighar",
  "Kamaldi",
  "Asan",
  "Naxal",
  "Maharajgunj",
  "Baluwatar",
  "Narayanhitti",
  "Gyaneshwor",
  "Bouddha",
  "Swyambhu",
  "Pepsi Cola",
  "Birendranagar",
  "Durbarmarga",
  "Sukedhara",
  "Balaju",
  "Maitidevi",
  "Old Baneshwor",
  "Putalisadak",
  "Ghantaghar",
  "Teku",
  "Kalanki",
  "Kalimati",
  "Anamnagar",
];
